version: '3.7'

services:
    springproject:
        build:
            context: .
            dockerfile: Dockerfile_springproject
            args:
                JAR_FILE: study-0.0.1-SNAPSHOT.jar
        image: phm0127/springproject:0.1
        ports: 
            - "8081:8080"
        container_name: springproject_green
